/**
 * Trigger a browser download for locally-generated bytes.
 *
 * Two details that are easy to get wrong and fail only on some browsers:
 *
 *  1. The anchor is attached to the document before clicking. A detached
 *     `<a>` is honoured by Chrome but historically ignored by Firefox.
 *  2. The object URL is revoked on a later task, not immediately after
 *     `click()`. Revoking synchronously races the browser's fetch of the blob;
 *     Firefox and Safari can cancel the download outright, which shows up as
 *     "nothing happened" on large exports and nowhere else.
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  // Long enough for the browser to have taken ownership of the blob, short
  // enough that the memory (a whole PDF) isn't held for any longer than needed.
  setTimeout(() => {
    a.remove();
    URL.revokeObjectURL(url);
  }, 10_000);
}

/** Download raw bytes with an explicit MIME type. */
export function downloadBytes(
  bytes: Uint8Array | ArrayBuffer,
  filename: string,
  mime = "application/pdf",
): void {
  downloadBlob(new Blob([bytes as BlobPart], { type: mime }), filename);
}

/** Download a UTF-8 text file. */
export function downloadText(text: string, filename: string): void {
  downloadBlob(new Blob([text], { type: "text/plain;charset=utf-8" }), filename);
}
